In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [2]:
x, y = make_classification(n_samples=5000, n_features=15, n_classes=2, random_state=42)

col_names = [f"feature_{i}" for i in range(1, 16)]

In [3]:
df = pd.DataFrame(x, columns=col_names)
df["target"] = y

df.head()

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,target
0,0.280547,0.513707,0.600077,0.132933,-0.446743,-0.024305,1.925692,-1.975469,1.465833,0.266588,2.244387,-1.704060,-0.530315,-1.162787,0.862646,1
1,0.504257,0.491558,-0.180046,-0.169979,-0.595169,0.224075,-0.612825,-1.086411,-0.209787,-0.315192,-0.706853,-1.858125,0.694097,0.714817,-0.291406,0
2,-0.146550,0.550992,-0.342294,-0.078793,-0.023507,1.978164,-1.415985,0.931033,1.248097,-0.404016,-0.700930,-0.556282,-0.065374,-0.026593,1.255934,0
3,-0.941686,1.515026,0.252214,-0.882632,-0.732410,-1.784526,1.096197,0.145569,-1.266551,1.754573,0.173466,-0.121218,2.750949,-1.439122,-0.754718,1
4,0.160889,-0.417992,-0.425010,0.991153,0.157452,2.544566,-1.772444,-0.534075,1.643475,-1.200643,-1.727058,-1.147564,0.994472,1.124417,-0.448450,0

In [4]:
x_train, x_test, y_train, y_test = train_test_split(x, y, stratify=y, test_size=0.20, random_state=42)

In [9]:
kernels = ["linear", "rbf"]
results = []

for kernel in kernels:
    model = Pipeline([
        ("scaler", StandardScaler()),
        ("svm", SVC(kernel=kernel, random_state=42))
    ])
    
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    
    accuracy = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    
    results.append({
        "kernel": kernel,
        "accuracy": accuracy,
        "f1_score": f1
    })
    
    print(f"Kernel: {kernel}")
    print(classification_report(y_test, y_pred))
    print("-" * 20)

Kernel: linear
              precision    recall  f1-score   support

           0       0.88      0.87      0.88       499
           1       0.87      0.88      0.88       501

    accuracy                           0.88      1000
   macro avg       0.88      0.88      0.88      1000
weighted avg       0.88      0.88      0.88      1000

--------------------
Kernel: rbf
              precision    recall  f1-score   support

           0       0.88      0.88      0.88       499
           1       0.88      0.88      0.88       501

    accuracy                           0.88      1000
   macro avg       0.88      0.88      0.88      1000
weighted avg       0.88      0.88      0.88      1000

--------------------

In [10]:
comparison_df = pd.DataFrame(results)
comparison_df

   kernel  accuracy  f1_score
0  linear     0.878  0.878968
1     rbf     0.880  0.880716